name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'bin/**'
      - 'README.md'

jobs:
  build:
    runs-on:
        - ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'
            
      - name: Install Node.js dependencies
        run: yarn install

      - name: Install Composer dependencies
        uses: php-actions/composer@v6

      - name: Run Unit Tests
        run: vendor/bin/phpunit --configuration phpunit.xml

      - name: Run Linter
        run: vendor/bin/phpcs --standard=PSR12 src/